#!/bin/sh
# File generated by ocamlbuild

cd '/home/tianchi/Cours/Reactive and Sychronous Systems/final project/mini-lustre/mini-lustre/examples'

rm -f pendulum.cmi
rm -f pendulum.cmo
# Also clean the script itself
rm -f '/home/tianchi/Cours/Reactive and Sychronous Systems/final project/mini-lustre/mini-lustre/examples/_build/sanitize.sh'
